FROM python:3.11-slim
WORKDIR /app
COPY main.py .
RUN pip install flask requests

# 声明构建参数（来自 build.yml）
ARG TG_BOT_TOKEN
ARG GITHUB_TOKEN
ARG ADMIN_ID
ARG WEBHOOK_URL
ARG REPO_CONFIG

# 在镜像内部定义环境变量
ENV TG_BOT_TOKEN=$TG_BOT_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ENV ADMIN_ID=$ADMIN_ID
ENV WEBHOOK_URL=$WEBHOOK_URL
ENV REPO_CONFIG=$REPO_CONFIG

EXPOSE 8000
CMD ["python", "main.py"]
